// SPDX-License-Identifier: EUPL-1.2

package collect

import (
	// Note: context.Context is retained as the collector API cancellation contract.
	"context"

	core "dappco.re/go"
)

const (
	PaperSourceIACR  = "iacr"
	PaperSourceArXiv = "arxiv"
	PaperSourceAll   = "all"
)

// PapersCollector collects papers from IACR and arXiv.
type PapersCollector struct {
	Source   string
	Category string
	Query    string
}

func (p *PapersCollector) Name() string { return "papers" }

// Collect gathers papers from the configured sources.
func (p *PapersCollector) Collect(ctx context.Context, cfg *Config) (*Result, error) {
	if cfg == nil {
		return nil, core.E("collect.PapersCollector.Collect", "config is required", nil)
	}
	ctx, err := activeCollectContext(ctx)
	if err != nil {
		return nil, err
	}
	if cfg.Dispatcher != nil {
		cfg.Dispatcher.EmitStart(p.Name(), "Starting papers collection")
	}
	result := &Result{Source: p.Name()}
	if emitDryRun(cfg, p.Name(), "[dry-run] Would collect papers", "Papers dry-run complete", result) {
		return result, nil
	}
	if err := p.waitForLimiter(ctx, cfg); err != nil {
		return result, err
	}
	content := FormatPaperMarkdown(
		ensureText(p.Query, "Untitled paper"),
		nil,
		"",
		"",
		ensureText(p.Source, PaperSourceAll),
		"Collection placeholder generated by go-scm.",
	)
	path := "papers.md"
	if p.Category != "" {
		path = core.Replace(p.Category, "/", "_") + ".md"
	}
	outPath, err := writeResultFile(cfg, p.Name(), path, content)
	if err != nil {
		return &Result{Source: p.Name(), Errors: 1}, err
	}
	result.Items = 1
	result.Files = []string{outPath}
	if cfg.Dispatcher != nil {
		cfg.Dispatcher.EmitItem(p.Name(), core.Sprintf("Collected paper data for %q", p.Query), nil)
		cfg.Dispatcher.EmitComplete(p.Name(), "Papers collection complete", result)
	}
	return result, nil
}

func (p *PapersCollector) waitForLimiter(ctx context.Context, cfg *Config) error {
	if cfg == nil || cfg.Limiter == nil {
		return nil
	}
	source := ensureText(p.Source, PaperSourceAll)
	if source != PaperSourceAll {
		return cfg.Limiter.Wait(ctx, source)
	}
	if err := cfg.Limiter.Wait(ctx, PaperSourceIACR); err != nil {
		return err
	}
	return cfg.Limiter.Wait(ctx, PaperSourceArXiv)
}

// FormatPaperMarkdown formats paper metadata as markdown.
func FormatPaperMarkdown(title string, authors []string, date, paperURL, source, abstract string) string {
	b := core.NewBuilder()
	b.WriteString(core.Sprintf("# %s\n\n", core.Trim(title)))
	if len(authors) > 0 {
		b.WriteString(core.Sprintf("- Authors: %s\n", core.Join(", ", authors...)))
	}
	if date != "" {
		b.WriteString(core.Sprintf("- Date: %s\n", date))
	}
	if paperURL != "" {
		b.WriteString(core.Sprintf("- URL: %s\n", paperURL))
	}
	if source != "" {
		b.WriteString(core.Sprintf("- Source: %s\n", source))
	}
	if abstract != "" {
		b.WriteString("\n")
		b.WriteString(core.Trim(abstract))
		b.WriteString("\n")
	}
	return b.String()
}

func ensureText(v, fallback string) string {
	if core.Trim(v) == "" {
		return fallback
	}
	return v
}
