// SPDX-License-Identifier: EUPL-1.2

package collect

import (
	// Note: context.Context is retained as the collector API cancellation contract.
	"context"
	// Note: errors.New is retained for stable collector validation errors.
	"errors"
	// Note: fmt.Fprintf/Sprintf are retained for Markdown and dispatcher message formatting in this load-bearing collector.
	"fmt"
	// Note: strings helpers are retained for paper metadata normalization and Markdown output.
	"strings"
)

const (
	PaperSourceIACR  = "iacr"
	PaperSourceArXiv = "arxiv"
	PaperSourceAll   = "all"
)

// PapersCollector collects papers from IACR and arXiv.
type PapersCollector struct {
	Source   string
	Category string
	Query    string
}

func (p *PapersCollector) Name() string { return "papers" }

// Collect gathers papers from the configured sources.
func (p *PapersCollector) Collect(ctx context.Context, cfg *Config) (*Result, error) {
	if cfg == nil {
		return nil, errors.New("collect.PapersCollector.Collect: config is required")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	if ctx != nil {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
	}
	if cfg.Dispatcher != nil {
		cfg.Dispatcher.EmitStart(p.Name(), "Starting papers collection")
	}
	if cfg.DryRun {
		if cfg.Dispatcher != nil {
			cfg.Dispatcher.EmitProgress(p.Name(), "[dry-run] Would collect papers", nil)
			cfg.Dispatcher.EmitComplete(p.Name(), "Papers dry-run complete", &Result{Source: p.Name()})
		}
		return &Result{Source: p.Name()}, nil
	}
	if cfg.Limiter != nil {
		source := ensureText(p.Source, PaperSourceAll)
		if source == PaperSourceAll {
			if err := cfg.Limiter.Wait(ctx, PaperSourceIACR); err != nil {
				return &Result{Source: p.Name()}, err
			}
			if err := cfg.Limiter.Wait(ctx, PaperSourceArXiv); err != nil {
				return &Result{Source: p.Name()}, err
			}
		} else if err := cfg.Limiter.Wait(ctx, source); err != nil {
			return &Result{Source: p.Name()}, err
		}
	}
	content := FormatPaperMarkdown(
		ensureText(p.Query, "Untitled paper"),
		nil,
		"",
		"",
		ensureText(p.Source, PaperSourceAll),
		"Collection placeholder generated by go-scm.",
	)
	path := "papers.md"
	if p.Category != "" {
		path = strings.ReplaceAll(p.Category, "/", "_") + ".md"
	}
	outPath, err := writeResultFile(cfg, p.Name(), path, content)
	if err != nil {
		return &Result{Source: p.Name(), Errors: 1}, err
	}
	result := &Result{Source: p.Name(), Items: 1, Files: []string{outPath}}
	if cfg.Dispatcher != nil {
		cfg.Dispatcher.EmitItem(p.Name(), fmt.Sprintf("Collected paper data for %q", p.Query), nil)
		cfg.Dispatcher.EmitComplete(p.Name(), "Papers collection complete", result)
	}
	return result, nil
}

// FormatPaperMarkdown formats paper metadata as markdown.
func FormatPaperMarkdown(title string, authors []string, date, paperURL, source, abstract string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", strings.TrimSpace(title))
	if len(authors) > 0 {
		fmt.Fprintf(&b, "- Authors: %s\n", strings.Join(authors, ", "))
	}
	if date != "" {
		fmt.Fprintf(&b, "- Date: %s\n", date)
	}
	if paperURL != "" {
		fmt.Fprintf(&b, "- URL: %s\n", paperURL)
	}
	if source != "" {
		fmt.Fprintf(&b, "- Source: %s\n", source)
	}
	if abstract != "" {
		b.WriteString("\n")
		b.WriteString(strings.TrimSpace(abstract))
		b.WriteString("\n")
	}
	return b.String()
}

func ensureText(v, fallback string) string {
	if strings.TrimSpace(v) == "" {
		return fallback
	}
	return v
}
