// SPDX-License-Identifier: EUPL-1.2

package collect

import (
	"context"
	"errors"
	"fmt"
	"strings"
)

const (
	PaperSourceIACR  = "iacr"
	PaperSourceArXiv = "arxiv"
	PaperSourceAll   = "all"
)

// PapersCollector collects papers from IACR and arXiv.
type PapersCollector struct {
	Source   string
	Category string
	Query    string
}

func (p *PapersCollector) Name() string { return "papers" }

// Collect gathers papers from the configured sources.
func (p *PapersCollector) Collect(ctx context.Context, cfg *Config) (*Result, error) {
	if cfg == nil {
		return nil, errors.New("collect.PapersCollector.Collect: config is required")
	}
	if ctx != nil {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
	}
	content := FormatPaperMarkdown(
		ensureText(p.Query, "Untitled paper"),
		nil,
		"",
		"",
		ensureText(p.Source, PaperSourceAll),
		"Collection placeholder generated by go-scm.",
	)
	path := "papers.md"
	if p.Category != "" {
		path = strings.ReplaceAll(p.Category, "/", "_") + ".md"
	}
	outPath, err := writeResultFile(cfg, p.Name(), path, content)
	if err != nil {
		return &Result{Source: p.Name(), Errors: 1}, err
	}
	return &Result{Source: p.Name(), Items: 1, Files: []string{outPath}}, nil
}

// FormatPaperMarkdown formats paper metadata as markdown.
func FormatPaperMarkdown(title string, authors []string, date, paperURL, source, abstract string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", strings.TrimSpace(title))
	if len(authors) > 0 {
		fmt.Fprintf(&b, "- Authors: %s\n", strings.Join(authors, ", "))
	}
	if date != "" {
		fmt.Fprintf(&b, "- Date: %s\n", date)
	}
	if paperURL != "" {
		fmt.Fprintf(&b, "- URL: %s\n", paperURL)
	}
	if source != "" {
		fmt.Fprintf(&b, "- Source: %s\n", source)
	}
	if abstract != "" {
		b.WriteString("\n")
		b.WriteString(strings.TrimSpace(abstract))
		b.WriteString("\n")
	}
	return b.String()
}

func ensureText(v, fallback string) string {
	if strings.TrimSpace(v) == "" {
		return fallback
	}
	return v
}
